// Generated by CoffeeScript 1.7.1
(function() {
  App.Branding = (function() {
    function Branding(el) {
      this.el = $(el);
      this.window = $(window);
      this.resize();
      this.window.resize((function(_this) {
        return function() {
          return _this.resize();
        };
      })(this));
      return;
    }

    Branding.prototype.resize = function() {
      var padding;
      padding = (this.window.height() - this.el.height()) / 2;
      this.el.css({
        "padding-top": padding - this.el.offset().top,
        "padding-bottom": padding
      });
    };

    return Branding;

  })();

}).call(this);
