// Generated by CoffeeScript 1.7.1
(function() {
  App.Branding = (function() {
    function Branding(el) {
      this.el = $(el);
      this.window = $(window);
      this.offset = this.el.height() + this.el.offset().top;
      this.resize();
      this.window.resize((function(_this) {
        return function() {
          return _this.resize();
        };
      })(this));
      return;
    }

    Branding.prototype.resize = function() {
      var value;
      value = ((this.window.height()) - this.offset) / 2;
      if (value < 0) {
        value = 0;
      }
      this.el.css({
        "padding-top": value,
        "padding-bottom": value
      });
    };

    return Branding;

  })();

}).call(this);
